// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TomNextPortfolioAssets.EF;

#nullable disable

namespace TomNextPortfolioAssets.EF.Migrations
{
    [DbContext(typeof(TomNextPortfolioAssetsDbContext))]
    [Migration("20260129064248_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TomNextPortfolioAssets.Domain.Tables.AssetNewsMatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<List<string>>("MatchedFields")
                        .HasColumnType("text[]");

                    b.Property<Guid>("NewsArticleId")
                        .HasColumnType("uuid");

                    b.Property<int>("RelevanceScore")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssetId");

                    b.HasIndex("NewsArticleId");

                    b.ToTable("AssetsNewMatch");
                });

            modelBuilder.Entity("TomNextPortfolioAssets.Domain.Tables.Assets", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssetClass")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FundName")
                        .HasColumnType("text");

                    b.Property<string>("Geography")
                        .HasColumnType("text");

                    b.Property<List<string>>("Keywords")
                        .HasColumnType("text[]");

                    b.Property<string>("Manager")
                        .HasColumnType("text");

                    b.Property<List<string>>("Sectors")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            Id = new Guid("8051e63c-04c2-49d0-830e-968e19ee594d"),
                            AssetClass = "1",
                            CreatedAt = new DateTime(2026, 1, 27, 12, 45, 48, 0, DateTimeKind.Utc),
                            FundName = "MMC EIS Fund",
                            Geography = "GB",
                            Keywords = new List<string> { "global stocks", "equity growth" },
                            Manager = "Parimal",
                            Sectors = new List<string> { "Technology", "Healthcare" }
                        },
                        new
                        {
                            Id = new Guid("6c3e0d72-ee26-4e29-8283-9964f01d5658"),
                            AssetClass = "3",
                            CreatedAt = new DateTime(2026, 1, 27, 12, 50, 59, 0, DateTimeKind.Utc),
                            FundName = "Emerging Markets Growth Fund",
                            Geography = "EMEA",
                            Keywords = new List<string> { "emerging economies", "market growth", "developing nations" },
                            Manager = "Rahul",
                            Sectors = new List<string> { "Financials", "Energy", "Industrials" }
                        },
                        new
                        {
                            Id = new Guid("7071195d-7354-43b0-a38d-584b12ae5cec"),
                            AssetClass = "4",
                            CreatedAt = new DateTime(2026, 1, 27, 12, 50, 59, 0, DateTimeKind.Utc),
                            FundName = "Global Corporate Bond Fund",
                            Geography = "Global",
                            Keywords = new List<string> { "bond yields", "interest rates", "fixed income investing" },
                            Manager = "Parimal",
                            Sectors = new List<string> { "Corporate Bonds", "Finance", "Utilities" }
                        },
                        new
                        {
                            Id = new Guid("12e62a7a-9ae9-4f75-93e4-e456987c13a7"),
                            AssetClass = "5",
                            CreatedAt = new DateTime(2026, 1, 27, 12, 50, 59, 0, DateTimeKind.Utc),
                            FundName = "Sustainable Energy Fund",
                            Geography = "Global",
                            Keywords = new List<string> { "green energy", "ESG investing", "sustainability" },
                            Manager = "Darshan",
                            Sectors = new List<string> { "Renewable Energy", "Clean Tech", "Utilities" }
                        },
                        new
                        {
                            Id = new Guid("8d3c9203-7754-428e-b54f-20757bef855c"),
                            AssetClass = "2",
                            CreatedAt = new DateTime(2026, 1, 27, 12, 48, 58, 0, DateTimeKind.Utc),
                            FundName = "Global Tech Innovation Fund",
                            Geography = "US",
                            Keywords = new List<string> { "artificial intelligence", "tech growth", "chip makers" },
                            Manager = "BlackRock",
                            Sectors = new List<string> { "Technology", "AI", "Semiconductors" }
                        });
                });

            modelBuilder.Entity("TomNextPortfolioAssets.Domain.Tables.NewsArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Geo")
                        .HasColumnType("text");

                    b.Property<DateTime>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RawContent")
                        .HasColumnType("text");

                    b.Property<string>("Sector")
                        .HasColumnType("text");

                    b.Property<string>("Snippet")
                        .HasColumnType("text");

                    b.Property<string>("Source")
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("NewsArticles");
                });

            modelBuilder.Entity("TomNextPortfolioAssets.Domain.Tables.UserNewsState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsPinned")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NewsArticleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("UserNewsStates");
                });

            modelBuilder.Entity("TomNextPortfolioAssets.Domain.Tables.AssetNewsMatch", b =>
                {
                    b.HasOne("TomNextPortfolioAssets.Domain.Tables.Assets", "Asset")
                        .WithMany("Matches")
                        .HasForeignKey("AssetId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TomNextPortfolioAssets.Domain.Tables.NewsArticle", "NewsArticle")
                        .WithMany("Matches")
                        .HasForeignKey("NewsArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asset");

                    b.Navigation("NewsArticle");
                });

            modelBuilder.Entity("TomNextPortfolioAssets.Domain.Tables.Assets", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("TomNextPortfolioAssets.Domain.Tables.NewsArticle", b =>
                {
                    b.Navigation("Matches");
                });
#pragma warning restore 612, 618
        }
    }
}
